baseURL: 'https://janettemujica.github.io/myacademicwebsite/'
title: Janette Mujica
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: papers
      url: papers/
      weight: 1
    - name: contributions
      url: contributions/
      weight: 2
    - name: teaching
      url: teaching/
      weight: 3

params:
  description: "This website hosts Janette Mujica's research papers, contributions, and teaching experiences."
  author: Janette Mujica
  # googleAnalyticsID: G-XXXXX
  DateFormat: January 2006
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: [papers, contributions, teaching]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Janette Mujica
    subtitle: I am a first-year [PhD student in Digital Transformation and Innovation](https://dtiuottawa.ca/student/janette-mujica/) at the University of Ottawa. I study how patients, clinicians, and engineers co-design AI self-care chatbots for chronic conditions. My goal is to help those developing AI technologies meaningfully include end users to align with their best interests. <br><br> I am fortunate to be supervised by Professor [Sylvie Grosjean](https://uniweb.uottawa.ca/view/profile/members/721), and to have Professors [Lysanne Lessard](https://telfer.uottawa.ca/en/directory/lysanne-lessard/) and [Mayur Joshi](https://telfer.uottawa.ca/en/directory/mayur-joshi/) on my doctoral committee, whose expertise spans socio-technical design, digitally enabled services and technology & organizing.
    bio:
      Since fall 2024, I have worked as a research assistant at the Com&Tech Innovation Lab, directed by [Sylvie Grosjean](https://uniweb.uottawa.ca/view/profile/members/721), codesigning self-care technologies for people living with Parkinson’s. I have gained experience in qualitative research, participatory design and prototyping, transforming qualitative insights into tangible outcomes.<br><br> Alongside my master's and doctoral studies in Digital Transformation and Innovation, I completed training in Innovation Management at HEC Montréal, Digital Humanities and Computer Science at Université de Montréal. Before academia, I worked for more than a decade as an executive assistant in consulting, legal, financial organizations which have enhanced my ability to work across professional cultures.<br><br>

      I study AI chatbots, which are becoming increasingly popular in healthcare and represent a socio-technical phenomenon. People, especially those living in underserved rural areas or seeking information outside clinic hours, are reported to use chatbots for health-related questions. However, health professionals are expressing concerns about the risks, such as inaccurate or unreliable information. This issue is significant in Canada, where around 44% of adults over 20 live with at least one chronic condition.<br><br>

      As people live longer with these conditions, healthcare systems face increasing demands. Some people are optimistic that AI chatbots can help alleviate this burden. Others express concerns that end-users such as patients are not be meaningfully involved in the development and governance of AI tools, which goes against their best interests.
    imageUrl: picture.jpeg
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: papers
        url: papers/
      - name: contributions
        url: contributions/
      - name: teaching
        url: teaching/

  socialIcons:
    - name: LinkedIn
      url: https://www.linkedin.com/in/janettemujica/
    - name: Email
      url: mailto:mujica.janette@gmail.com
    - name: Google Scholar
      url: https://scholar.google.ca/citations?hl=fr&user=MT42rVcAAAAJ&view_op=list_works&gmla=AKCpqFzhOriNt5vhO_VdHF330ipq_L7jlpBTTtmGJ_CHXvI1Rsfjmfp6gjYQZxrebRe8kwnj3JVbF5qTdqfipWhp0sK_oPTIJzO3xeA-wv6WICArLg
    - name: GitHub
      url: https://github.com/JanetteMujica

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: Janette Mujica
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
